default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: postgres
  password: Elevate2023

development:
  <<: *default
  database: new_car_data
  host: localhost